//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASMXinSharePointEr.CASService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://IntegrationLayer.Portal/", ConfigurationName="CASService.IntegrationService_UserSoap")]
    public interface IntegrationService_UserSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://IntegrationLayer.Portal/GetListOfUsers", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ASMXinSharePointEr.CASService.UserAccount[] GetListOfUsers(string PortalUser, string PortalPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://IntegrationLayer.Portal/GetListOfUsers", ReplyAction="*")]
        System.Threading.Tasks.Task<ASMXinSharePointEr.CASService.UserAccount[]> GetListOfUsersAsync(string PortalUser, string PortalPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://IntegrationLayer.Portal/GetUserAccount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ASMXinSharePointEr.CASService.UserAccount GetUserAccount(string PortalUser, string PortalPassword, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://IntegrationLayer.Portal/GetUserAccount", ReplyAction="*")]
        System.Threading.Tasks.Task<ASMXinSharePointEr.CASService.UserAccount> GetUserAccountAsync(string PortalUser, string PortalPassword, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://IntegrationLayer.Portal/RegisterUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ASMXinSharePointEr.CASService.ResultRegisterUser RegisterUser(string PortalUser, string PortalPassword, string username, string password, string name, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://IntegrationLayer.Portal/RegisterUser", ReplyAction="*")]
        System.Threading.Tasks.Task<ASMXinSharePointEr.CASService.ResultRegisterUser> RegisterUserAsync(string PortalUser, string PortalPassword, string username, string password, string name, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://IntegrationLayer.Portal/ValidateUserPass", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ValidateUserPass(string PortalUser, string PortalPassword, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://IntegrationLayer.Portal/ValidateUserPass", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ValidateUserPassAsync(string PortalUser, string PortalPassword, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://IntegrationLayer.Portal/GetUserProfile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ASMXinSharePointEr.CASService.ResultGetUserProfile GetUserProfile(string PortalUser, string PortalPassword, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://IntegrationLayer.Portal/GetUserProfile", ReplyAction="*")]
        System.Threading.Tasks.Task<ASMXinSharePointEr.CASService.ResultGetUserProfile> GetUserProfileAsync(string PortalUser, string PortalPassword, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://IntegrationLayer.Portal/GetProfileByUsername", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ASMXinSharePointEr.CASService.UserProfile GetProfileByUsername(string PortalUser, string PortalPassword, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://IntegrationLayer.Portal/GetProfileByUsername", ReplyAction="*")]
        System.Threading.Tasks.Task<ASMXinSharePointEr.CASService.UserProfile> GetProfileByUsernameAsync(string PortalUser, string PortalPassword, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://IntegrationLayer.Portal/GetProfileByNationalCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ASMXinSharePointEr.CASService.UserProfile GetProfileByNationalCode(string PortalUser, string PortalPassword, string nationalCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://IntegrationLayer.Portal/GetProfileByNationalCode", ReplyAction="*")]
        System.Threading.Tasks.Task<ASMXinSharePointEr.CASService.UserProfile> GetProfileByNationalCodeAsync(string PortalUser, string PortalPassword, string nationalCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://IntegrationLayer.Portal/GetProfileByMobileNumber", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ASMXinSharePointEr.CASService.UserProfile GetProfileByMobileNumber(string PortalUser, string PortalPassword, string mobileNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://IntegrationLayer.Portal/GetProfileByMobileNumber", ReplyAction="*")]
        System.Threading.Tasks.Task<ASMXinSharePointEr.CASService.UserProfile> GetProfileByMobileNumberAsync(string PortalUser, string PortalPassword, string mobileNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://IntegrationLayer.Portal/ChangeStatus137", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ChangeStatus137(string PortalUser, string PortalPassword, string tracking_id, string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://IntegrationLayer.Portal/ChangeStatus137", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ChangeStatus137Async(string PortalUser, string PortalPassword, string tracking_id, string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://IntegrationLayer.Portal/GetAuthenticatedUserBySessionID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ASMXinSharePointEr.CASService.ResultGetAuthenticatedUserBySessionID GetAuthenticatedUserBySessionID(string PortalUser, string PortalPassword, string session);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://IntegrationLayer.Portal/GetAuthenticatedUserBySessionID", ReplyAction="*")]
        System.Threading.Tasks.Task<ASMXinSharePointEr.CASService.ResultGetAuthenticatedUserBySessionID> GetAuthenticatedUserBySessionIDAsync(string PortalUser, string PortalPassword, string session);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://IntegrationLayer.Portal/GetPasmandInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ASMXinSharePointEr.CASService.PasmandInfo GetPasmandInfo(string PortalUser, string PortalPassword, string nationalCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://IntegrationLayer.Portal/GetPasmandInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<ASMXinSharePointEr.CASService.PasmandInfo> GetPasmandInfoAsync(string PortalUser, string PortalPassword, string nationalCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://IntegrationLayer.Portal/GetTopPasmandUsers", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ASMXinSharePointEr.CASService.PasmandUser[] GetTopPasmandUsers(string PortalUser, string PortalPassword, int days, int limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://IntegrationLayer.Portal/GetTopPasmandUsers", ReplyAction="*")]
        System.Threading.Tasks.Task<ASMXinSharePointEr.CASService.PasmandUser[]> GetTopPasmandUsersAsync(string PortalUser, string PortalPassword, int days, int limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://IntegrationLayer.Portal/Test", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ASMXinSharePointEr.CASService.TestResponse Test(ASMXinSharePointEr.CASService.TestRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://IntegrationLayer.Portal/Test", ReplyAction="*")]
        System.Threading.Tasks.Task<ASMXinSharePointEr.CASService.TestResponse> TestAsync(ASMXinSharePointEr.CASService.TestRequest request);
        
        // CODEGEN: Generating message contract since message RandomRequestTestRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://IntegrationLayer.Portal/RandomRequestTest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ASMXinSharePointEr.CASService.RandomRequestTestResponse RandomRequestTest(ASMXinSharePointEr.CASService.RandomRequestTestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://IntegrationLayer.Portal/RandomRequestTest", ReplyAction="*")]
        System.Threading.Tasks.Task<ASMXinSharePointEr.CASService.RandomRequestTestResponse> RandomRequestTestAsync(ASMXinSharePointEr.CASService.RandomRequestTestRequest request);
        
        // CODEGEN: Generating message contract since message isTokenAuthorizedRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://IntegrationLayer.Portal/isTokenAuthorized", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ASMXinSharePointEr.CASService.isTokenAuthorizedResponse isTokenAuthorized(ASMXinSharePointEr.CASService.isTokenAuthorizedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://IntegrationLayer.Portal/isTokenAuthorized", ReplyAction="*")]
        System.Threading.Tasks.Task<ASMXinSharePointEr.CASService.isTokenAuthorizedResponse> isTokenAuthorizedAsync(ASMXinSharePointEr.CASService.isTokenAuthorizedRequest request);
        
        // CODEGEN: Generating message contract since message isTokenAuthorizedForMethodRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://IntegrationLayer.Portal/isTokenAuthorizedForMethod", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ASMXinSharePointEr.CASService.isTokenAuthorizedForMethodResponse isTokenAuthorizedForMethod(ASMXinSharePointEr.CASService.isTokenAuthorizedForMethodRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://IntegrationLayer.Portal/isTokenAuthorizedForMethod", ReplyAction="*")]
        System.Threading.Tasks.Task<ASMXinSharePointEr.CASService.isTokenAuthorizedForMethodResponse> isTokenAuthorizedForMethodAsync(ASMXinSharePointEr.CASService.isTokenAuthorizedForMethodRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://IntegrationLayer.Portal/")]
    public partial class UserAccount : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<long> uIDField;
        
        private string fullNameField;
        
        private string userNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<long> UID {
            get {
                return this.uIDField;
            }
            set {
                this.uIDField = value;
                this.RaisePropertyChanged("UID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FullName {
            get {
                return this.fullNameField;
            }
            set {
                this.fullNameField = value;
                this.RaisePropertyChanged("FullName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://IntegrationLayer.Portal/")]
    public partial class ExecutionCondition : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<System.DateTime> executableFromField;
        
        private System.Nullable<System.DateTime> executableUntilField;
        
        private System.Nullable<System.Guid> executionDependOnField;
        
        private System.Nullable<int> totalTrysField;
        
        private System.Nullable<int> reTryIntervalField;
        
        private FailNotifyTypes failNotifyTypeField;
        
        private string callBackUrlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<System.DateTime> ExecutableFrom {
            get {
                return this.executableFromField;
            }
            set {
                this.executableFromField = value;
                this.RaisePropertyChanged("ExecutableFrom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<System.DateTime> ExecutableUntil {
            get {
                return this.executableUntilField;
            }
            set {
                this.executableUntilField = value;
                this.RaisePropertyChanged("ExecutableUntil");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<System.Guid> ExecutionDependOn {
            get {
                return this.executionDependOnField;
            }
            set {
                this.executionDependOnField = value;
                this.RaisePropertyChanged("ExecutionDependOn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<int> TotalTrys {
            get {
                return this.totalTrysField;
            }
            set {
                this.totalTrysField = value;
                this.RaisePropertyChanged("TotalTrys");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<int> ReTryInterval {
            get {
                return this.reTryIntervalField;
            }
            set {
                this.reTryIntervalField = value;
                this.RaisePropertyChanged("ReTryInterval");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public FailNotifyTypes FailNotifyType {
            get {
                return this.failNotifyTypeField;
            }
            set {
                this.failNotifyTypeField = value;
                this.RaisePropertyChanged("FailNotifyType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string CallBackUrl {
            get {
                return this.callBackUrlField;
            }
            set {
                this.callBackUrlField = value;
                this.RaisePropertyChanged("CallBackUrl");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://IntegrationLayer.Portal/")]
    public enum FailNotifyTypes {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        SMS,
        
        /// <remarks/>
        EMail,
        
        /// <remarks/>
        SMSAndEMail,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://IntegrationLayer.Portal/")]
    public partial class SoapToken : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tokenIDField;
        
        private System.Nullable<bool> requestSEQField;
        
        private ExecutionCondition sEQExecutionConditionField;
        
        private System.Nullable<System.Guid> sEQIDField;
        
        private System.Nullable<bool> useCacheField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string TokenID {
            get {
                return this.tokenIDField;
            }
            set {
                this.tokenIDField = value;
                this.RaisePropertyChanged("TokenID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<bool> RequestSEQ {
            get {
                return this.requestSEQField;
            }
            set {
                this.requestSEQField = value;
                this.RaisePropertyChanged("RequestSEQ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public ExecutionCondition SEQExecutionCondition {
            get {
                return this.sEQExecutionConditionField;
            }
            set {
                this.sEQExecutionConditionField = value;
                this.RaisePropertyChanged("SEQExecutionCondition");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<System.Guid> SEQID {
            get {
                return this.sEQIDField;
            }
            set {
                this.sEQIDField = value;
                this.RaisePropertyChanged("SEQID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<bool> UseCache {
            get {
                return this.useCacheField;
            }
            set {
                this.useCacheField = value;
                this.RaisePropertyChanged("UseCache");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://IntegrationLayer.Portal/")]
    public partial class PasmandUser : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string nameField;
        
        private int scoreField;
        
        private int rankField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Score {
            get {
                return this.scoreField;
            }
            set {
                this.scoreField = value;
                this.RaisePropertyChanged("Score");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Rank {
            get {
                return this.rankField;
            }
            set {
                this.rankField = value;
                this.RaisePropertyChanged("Rank");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://IntegrationLayer.Portal/")]
    public partial class PasmandInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string hamyarPasmandScoreField;
        
        private string totalScoreField;
        
        private string serialCountField;
        
        private string iconURLField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string HamyarPasmandScore {
            get {
                return this.hamyarPasmandScoreField;
            }
            set {
                this.hamyarPasmandScoreField = value;
                this.RaisePropertyChanged("HamyarPasmandScore");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string TotalScore {
            get {
                return this.totalScoreField;
            }
            set {
                this.totalScoreField = value;
                this.RaisePropertyChanged("TotalScore");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SerialCount {
            get {
                return this.serialCountField;
            }
            set {
                this.serialCountField = value;
                this.RaisePropertyChanged("SerialCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string IconURL {
            get {
                return this.iconURLField;
            }
            set {
                this.iconURLField = value;
                this.RaisePropertyChanged("IconURL");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://IntegrationLayer.Portal/")]
    public partial class ResultGetAuthenticatedUserBySessionID : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool statusField;
        
        private string usernameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://IntegrationLayer.Portal/")]
    public partial class UserProfile : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userNameField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string mobileNumberField;
        
        private string emailField;
        
        private bool isEmployeeField;
        
        private string nationalCodeField;
        
        private string birthDateField;
        
        private Image avatarField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("FirstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("LastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string MobileNumber {
            get {
                return this.mobileNumberField;
            }
            set {
                this.mobileNumberField = value;
                this.RaisePropertyChanged("MobileNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool IsEmployee {
            get {
                return this.isEmployeeField;
            }
            set {
                this.isEmployeeField = value;
                this.RaisePropertyChanged("IsEmployee");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string NationalCode {
            get {
                return this.nationalCodeField;
            }
            set {
                this.nationalCodeField = value;
                this.RaisePropertyChanged("NationalCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string BirthDate {
            get {
                return this.birthDateField;
            }
            set {
                this.birthDateField = value;
                this.RaisePropertyChanged("BirthDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public Image Avatar {
            get {
                return this.avatarField;
            }
            set {
                this.avatarField = value;
                this.RaisePropertyChanged("Avatar");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://IntegrationLayer.Portal/")]
    public partial class Image : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tinyField;
        
        private string smallField;
        
        private string mediumField;
        
        private string largeField;
        
        private string masterField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Tiny {
            get {
                return this.tinyField;
            }
            set {
                this.tinyField = value;
                this.RaisePropertyChanged("Tiny");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Small {
            get {
                return this.smallField;
            }
            set {
                this.smallField = value;
                this.RaisePropertyChanged("Small");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Medium {
            get {
                return this.mediumField;
            }
            set {
                this.mediumField = value;
                this.RaisePropertyChanged("Medium");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Large {
            get {
                return this.largeField;
            }
            set {
                this.largeField = value;
                this.RaisePropertyChanged("Large");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Master {
            get {
                return this.masterField;
            }
            set {
                this.masterField = value;
                this.RaisePropertyChanged("Master");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://IntegrationLayer.Portal/")]
    public partial class ResultGetUserProfile : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userNameField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string mobileNumberField;
        
        private bool isEmployeeField;
        
        private string nationalCodeField;
        
        private Image avatarField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("FirstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("LastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string MobileNumber {
            get {
                return this.mobileNumberField;
            }
            set {
                this.mobileNumberField = value;
                this.RaisePropertyChanged("MobileNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool IsEmployee {
            get {
                return this.isEmployeeField;
            }
            set {
                this.isEmployeeField = value;
                this.RaisePropertyChanged("IsEmployee");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string NationalCode {
            get {
                return this.nationalCodeField;
            }
            set {
                this.nationalCodeField = value;
                this.RaisePropertyChanged("NationalCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public Image Avatar {
            get {
                return this.avatarField;
            }
            set {
                this.avatarField = value;
                this.RaisePropertyChanged("Avatar");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://IntegrationLayer.Portal/")]
    public partial class ResultRegisterUser : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool statusField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Test", WrapperNamespace="http://IntegrationLayer.Portal/", IsWrapped=true)]
    public partial class TestRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://IntegrationLayer.Portal/")]
        public ASMXinSharePointEr.CASService.SoapToken SoapToken;
        
        public TestRequest() {
        }
        
        public TestRequest(ASMXinSharePointEr.CASService.SoapToken SoapToken) {
            this.SoapToken = SoapToken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TestResponse", WrapperNamespace="http://IntegrationLayer.Portal/", IsWrapped=true)]
    public partial class TestResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://IntegrationLayer.Portal/")]
        public ASMXinSharePointEr.CASService.SoapToken SoapToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://IntegrationLayer.Portal/", Order=0)]
        public int TestResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://IntegrationLayer.Portal/", Order=1)]
        public string AdditionalInfo;
        
        public TestResponse() {
        }
        
        public TestResponse(ASMXinSharePointEr.CASService.SoapToken SoapToken, int TestResult, string AdditionalInfo) {
            this.SoapToken = SoapToken;
            this.TestResult = TestResult;
            this.AdditionalInfo = AdditionalInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RandomRequestTest", WrapperNamespace="http://IntegrationLayer.Portal/", IsWrapped=true)]
    public partial class RandomRequestTestRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://IntegrationLayer.Portal/")]
        public ASMXinSharePointEr.CASService.SoapToken SoapToken;
        
        public RandomRequestTestRequest() {
        }
        
        public RandomRequestTestRequest(ASMXinSharePointEr.CASService.SoapToken SoapToken) {
            this.SoapToken = SoapToken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RandomRequestTestResponse", WrapperNamespace="http://IntegrationLayer.Portal/", IsWrapped=true)]
    public partial class RandomRequestTestResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://IntegrationLayer.Portal/")]
        public ASMXinSharePointEr.CASService.SoapToken SoapToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://IntegrationLayer.Portal/", Order=0)]
        public int RandomRequestTestResult;
        
        public RandomRequestTestResponse() {
        }
        
        public RandomRequestTestResponse(ASMXinSharePointEr.CASService.SoapToken SoapToken, int RandomRequestTestResult) {
            this.SoapToken = SoapToken;
            this.RandomRequestTestResult = RandomRequestTestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="isTokenAuthorized", WrapperNamespace="http://IntegrationLayer.Portal/", IsWrapped=true)]
    public partial class isTokenAuthorizedRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://IntegrationLayer.Portal/")]
        public ASMXinSharePointEr.CASService.SoapToken SoapToken;
        
        public isTokenAuthorizedRequest() {
        }
        
        public isTokenAuthorizedRequest(ASMXinSharePointEr.CASService.SoapToken SoapToken) {
            this.SoapToken = SoapToken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="isTokenAuthorizedResponse", WrapperNamespace="http://IntegrationLayer.Portal/", IsWrapped=true)]
    public partial class isTokenAuthorizedResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://IntegrationLayer.Portal/")]
        public ASMXinSharePointEr.CASService.SoapToken SoapToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://IntegrationLayer.Portal/", Order=0)]
        public bool isTokenAuthorizedResult;
        
        public isTokenAuthorizedResponse() {
        }
        
        public isTokenAuthorizedResponse(ASMXinSharePointEr.CASService.SoapToken SoapToken, bool isTokenAuthorizedResult) {
            this.SoapToken = SoapToken;
            this.isTokenAuthorizedResult = isTokenAuthorizedResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="isTokenAuthorizedForMethod", WrapperNamespace="http://IntegrationLayer.Portal/", IsWrapped=true)]
    public partial class isTokenAuthorizedForMethodRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://IntegrationLayer.Portal/")]
        public ASMXinSharePointEr.CASService.SoapToken SoapToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://IntegrationLayer.Portal/", Order=0)]
        public string MethodName;
        
        public isTokenAuthorizedForMethodRequest() {
        }
        
        public isTokenAuthorizedForMethodRequest(ASMXinSharePointEr.CASService.SoapToken SoapToken, string MethodName) {
            this.SoapToken = SoapToken;
            this.MethodName = MethodName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="isTokenAuthorizedForMethodResponse", WrapperNamespace="http://IntegrationLayer.Portal/", IsWrapped=true)]
    public partial class isTokenAuthorizedForMethodResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://IntegrationLayer.Portal/")]
        public ASMXinSharePointEr.CASService.SoapToken SoapToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://IntegrationLayer.Portal/", Order=0)]
        public bool isTokenAuthorizedForMethodResult;
        
        public isTokenAuthorizedForMethodResponse() {
        }
        
        public isTokenAuthorizedForMethodResponse(ASMXinSharePointEr.CASService.SoapToken SoapToken, bool isTokenAuthorizedForMethodResult) {
            this.SoapToken = SoapToken;
            this.isTokenAuthorizedForMethodResult = isTokenAuthorizedForMethodResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IntegrationService_UserSoapChannel : ASMXinSharePointEr.CASService.IntegrationService_UserSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IntegrationService_UserSoapClient : System.ServiceModel.ClientBase<ASMXinSharePointEr.CASService.IntegrationService_UserSoap>, ASMXinSharePointEr.CASService.IntegrationService_UserSoap {
        
        public IntegrationService_UserSoapClient() {
        }
        
        public IntegrationService_UserSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IntegrationService_UserSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IntegrationService_UserSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IntegrationService_UserSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ASMXinSharePointEr.CASService.UserAccount[] GetListOfUsers(string PortalUser, string PortalPassword) {
            return base.Channel.GetListOfUsers(PortalUser, PortalPassword);
        }
        
        public System.Threading.Tasks.Task<ASMXinSharePointEr.CASService.UserAccount[]> GetListOfUsersAsync(string PortalUser, string PortalPassword) {
            return base.Channel.GetListOfUsersAsync(PortalUser, PortalPassword);
        }
        
        public ASMXinSharePointEr.CASService.UserAccount GetUserAccount(string PortalUser, string PortalPassword, string username) {
            return base.Channel.GetUserAccount(PortalUser, PortalPassword, username);
        }
        
        public System.Threading.Tasks.Task<ASMXinSharePointEr.CASService.UserAccount> GetUserAccountAsync(string PortalUser, string PortalPassword, string username) {
            return base.Channel.GetUserAccountAsync(PortalUser, PortalPassword, username);
        }
        
        public ASMXinSharePointEr.CASService.ResultRegisterUser RegisterUser(string PortalUser, string PortalPassword, string username, string password, string name, string email) {
            return base.Channel.RegisterUser(PortalUser, PortalPassword, username, password, name, email);
        }
        
        public System.Threading.Tasks.Task<ASMXinSharePointEr.CASService.ResultRegisterUser> RegisterUserAsync(string PortalUser, string PortalPassword, string username, string password, string name, string email) {
            return base.Channel.RegisterUserAsync(PortalUser, PortalPassword, username, password, name, email);
        }
        
        public bool ValidateUserPass(string PortalUser, string PortalPassword, string username, string password) {
            return base.Channel.ValidateUserPass(PortalUser, PortalPassword, username, password);
        }
        
        public System.Threading.Tasks.Task<bool> ValidateUserPassAsync(string PortalUser, string PortalPassword, string username, string password) {
            return base.Channel.ValidateUserPassAsync(PortalUser, PortalPassword, username, password);
        }
        
        public ASMXinSharePointEr.CASService.ResultGetUserProfile GetUserProfile(string PortalUser, string PortalPassword, string username) {
            return base.Channel.GetUserProfile(PortalUser, PortalPassword, username);
        }
        
        public System.Threading.Tasks.Task<ASMXinSharePointEr.CASService.ResultGetUserProfile> GetUserProfileAsync(string PortalUser, string PortalPassword, string username) {
            return base.Channel.GetUserProfileAsync(PortalUser, PortalPassword, username);
        }
        
        public ASMXinSharePointEr.CASService.UserProfile GetProfileByUsername(string PortalUser, string PortalPassword, string username) {
            return base.Channel.GetProfileByUsername(PortalUser, PortalPassword, username);
        }
        
        public System.Threading.Tasks.Task<ASMXinSharePointEr.CASService.UserProfile> GetProfileByUsernameAsync(string PortalUser, string PortalPassword, string username) {
            return base.Channel.GetProfileByUsernameAsync(PortalUser, PortalPassword, username);
        }
        
        public ASMXinSharePointEr.CASService.UserProfile GetProfileByNationalCode(string PortalUser, string PortalPassword, string nationalCode) {
            return base.Channel.GetProfileByNationalCode(PortalUser, PortalPassword, nationalCode);
        }
        
        public System.Threading.Tasks.Task<ASMXinSharePointEr.CASService.UserProfile> GetProfileByNationalCodeAsync(string PortalUser, string PortalPassword, string nationalCode) {
            return base.Channel.GetProfileByNationalCodeAsync(PortalUser, PortalPassword, nationalCode);
        }
        
        public ASMXinSharePointEr.CASService.UserProfile GetProfileByMobileNumber(string PortalUser, string PortalPassword, string mobileNumber) {
            return base.Channel.GetProfileByMobileNumber(PortalUser, PortalPassword, mobileNumber);
        }
        
        public System.Threading.Tasks.Task<ASMXinSharePointEr.CASService.UserProfile> GetProfileByMobileNumberAsync(string PortalUser, string PortalPassword, string mobileNumber) {
            return base.Channel.GetProfileByMobileNumberAsync(PortalUser, PortalPassword, mobileNumber);
        }
        
        public bool ChangeStatus137(string PortalUser, string PortalPassword, string tracking_id, string status) {
            return base.Channel.ChangeStatus137(PortalUser, PortalPassword, tracking_id, status);
        }
        
        public System.Threading.Tasks.Task<bool> ChangeStatus137Async(string PortalUser, string PortalPassword, string tracking_id, string status) {
            return base.Channel.ChangeStatus137Async(PortalUser, PortalPassword, tracking_id, status);
        }
        
        public ASMXinSharePointEr.CASService.ResultGetAuthenticatedUserBySessionID GetAuthenticatedUserBySessionID(string PortalUser, string PortalPassword, string session) {
            return base.Channel.GetAuthenticatedUserBySessionID(PortalUser, PortalPassword, session);
        }
        
        public System.Threading.Tasks.Task<ASMXinSharePointEr.CASService.ResultGetAuthenticatedUserBySessionID> GetAuthenticatedUserBySessionIDAsync(string PortalUser, string PortalPassword, string session) {
            return base.Channel.GetAuthenticatedUserBySessionIDAsync(PortalUser, PortalPassword, session);
        }
        
        public ASMXinSharePointEr.CASService.PasmandInfo GetPasmandInfo(string PortalUser, string PortalPassword, string nationalCode) {
            return base.Channel.GetPasmandInfo(PortalUser, PortalPassword, nationalCode);
        }
        
        public System.Threading.Tasks.Task<ASMXinSharePointEr.CASService.PasmandInfo> GetPasmandInfoAsync(string PortalUser, string PortalPassword, string nationalCode) {
            return base.Channel.GetPasmandInfoAsync(PortalUser, PortalPassword, nationalCode);
        }
        
        public ASMXinSharePointEr.CASService.PasmandUser[] GetTopPasmandUsers(string PortalUser, string PortalPassword, int days, int limit) {
            return base.Channel.GetTopPasmandUsers(PortalUser, PortalPassword, days, limit);
        }
        
        public System.Threading.Tasks.Task<ASMXinSharePointEr.CASService.PasmandUser[]> GetTopPasmandUsersAsync(string PortalUser, string PortalPassword, int days, int limit) {
            return base.Channel.GetTopPasmandUsersAsync(PortalUser, PortalPassword, days, limit);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ASMXinSharePointEr.CASService.TestResponse ASMXinSharePointEr.CASService.IntegrationService_UserSoap.Test(ASMXinSharePointEr.CASService.TestRequest request) {
            return base.Channel.Test(request);
        }
        
        public int Test(ref ASMXinSharePointEr.CASService.SoapToken SoapToken, out string AdditionalInfo) {
            ASMXinSharePointEr.CASService.TestRequest inValue = new ASMXinSharePointEr.CASService.TestRequest();
            inValue.SoapToken = SoapToken;
            ASMXinSharePointEr.CASService.TestResponse retVal = ((ASMXinSharePointEr.CASService.IntegrationService_UserSoap)(this)).Test(inValue);
            SoapToken = retVal.SoapToken;
            AdditionalInfo = retVal.AdditionalInfo;
            return retVal.TestResult;
        }
        
        public System.Threading.Tasks.Task<ASMXinSharePointEr.CASService.TestResponse> TestAsync(ASMXinSharePointEr.CASService.TestRequest request) {
            return base.Channel.TestAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ASMXinSharePointEr.CASService.RandomRequestTestResponse ASMXinSharePointEr.CASService.IntegrationService_UserSoap.RandomRequestTest(ASMXinSharePointEr.CASService.RandomRequestTestRequest request) {
            return base.Channel.RandomRequestTest(request);
        }
        
        public int RandomRequestTest(ref ASMXinSharePointEr.CASService.SoapToken SoapToken) {
            ASMXinSharePointEr.CASService.RandomRequestTestRequest inValue = new ASMXinSharePointEr.CASService.RandomRequestTestRequest();
            inValue.SoapToken = SoapToken;
            ASMXinSharePointEr.CASService.RandomRequestTestResponse retVal = ((ASMXinSharePointEr.CASService.IntegrationService_UserSoap)(this)).RandomRequestTest(inValue);
            SoapToken = retVal.SoapToken;
            return retVal.RandomRequestTestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ASMXinSharePointEr.CASService.RandomRequestTestResponse> ASMXinSharePointEr.CASService.IntegrationService_UserSoap.RandomRequestTestAsync(ASMXinSharePointEr.CASService.RandomRequestTestRequest request) {
            return base.Channel.RandomRequestTestAsync(request);
        }
        
        public System.Threading.Tasks.Task<ASMXinSharePointEr.CASService.RandomRequestTestResponse> RandomRequestTestAsync(ASMXinSharePointEr.CASService.SoapToken SoapToken) {
            ASMXinSharePointEr.CASService.RandomRequestTestRequest inValue = new ASMXinSharePointEr.CASService.RandomRequestTestRequest();
            inValue.SoapToken = SoapToken;
            return ((ASMXinSharePointEr.CASService.IntegrationService_UserSoap)(this)).RandomRequestTestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ASMXinSharePointEr.CASService.isTokenAuthorizedResponse ASMXinSharePointEr.CASService.IntegrationService_UserSoap.isTokenAuthorized(ASMXinSharePointEr.CASService.isTokenAuthorizedRequest request) {
            return base.Channel.isTokenAuthorized(request);
        }
        
        public bool isTokenAuthorized(ref ASMXinSharePointEr.CASService.SoapToken SoapToken) {
            ASMXinSharePointEr.CASService.isTokenAuthorizedRequest inValue = new ASMXinSharePointEr.CASService.isTokenAuthorizedRequest();
            inValue.SoapToken = SoapToken;
            ASMXinSharePointEr.CASService.isTokenAuthorizedResponse retVal = ((ASMXinSharePointEr.CASService.IntegrationService_UserSoap)(this)).isTokenAuthorized(inValue);
            SoapToken = retVal.SoapToken;
            return retVal.isTokenAuthorizedResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ASMXinSharePointEr.CASService.isTokenAuthorizedResponse> ASMXinSharePointEr.CASService.IntegrationService_UserSoap.isTokenAuthorizedAsync(ASMXinSharePointEr.CASService.isTokenAuthorizedRequest request) {
            return base.Channel.isTokenAuthorizedAsync(request);
        }
        
        public System.Threading.Tasks.Task<ASMXinSharePointEr.CASService.isTokenAuthorizedResponse> isTokenAuthorizedAsync(ASMXinSharePointEr.CASService.SoapToken SoapToken) {
            ASMXinSharePointEr.CASService.isTokenAuthorizedRequest inValue = new ASMXinSharePointEr.CASService.isTokenAuthorizedRequest();
            inValue.SoapToken = SoapToken;
            return ((ASMXinSharePointEr.CASService.IntegrationService_UserSoap)(this)).isTokenAuthorizedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ASMXinSharePointEr.CASService.isTokenAuthorizedForMethodResponse ASMXinSharePointEr.CASService.IntegrationService_UserSoap.isTokenAuthorizedForMethod(ASMXinSharePointEr.CASService.isTokenAuthorizedForMethodRequest request) {
            return base.Channel.isTokenAuthorizedForMethod(request);
        }
        
        public bool isTokenAuthorizedForMethod(ref ASMXinSharePointEr.CASService.SoapToken SoapToken, string MethodName) {
            ASMXinSharePointEr.CASService.isTokenAuthorizedForMethodRequest inValue = new ASMXinSharePointEr.CASService.isTokenAuthorizedForMethodRequest();
            inValue.SoapToken = SoapToken;
            inValue.MethodName = MethodName;
            ASMXinSharePointEr.CASService.isTokenAuthorizedForMethodResponse retVal = ((ASMXinSharePointEr.CASService.IntegrationService_UserSoap)(this)).isTokenAuthorizedForMethod(inValue);
            SoapToken = retVal.SoapToken;
            return retVal.isTokenAuthorizedForMethodResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ASMXinSharePointEr.CASService.isTokenAuthorizedForMethodResponse> ASMXinSharePointEr.CASService.IntegrationService_UserSoap.isTokenAuthorizedForMethodAsync(ASMXinSharePointEr.CASService.isTokenAuthorizedForMethodRequest request) {
            return base.Channel.isTokenAuthorizedForMethodAsync(request);
        }
        
        public System.Threading.Tasks.Task<ASMXinSharePointEr.CASService.isTokenAuthorizedForMethodResponse> isTokenAuthorizedForMethodAsync(ASMXinSharePointEr.CASService.SoapToken SoapToken, string MethodName) {
            ASMXinSharePointEr.CASService.isTokenAuthorizedForMethodRequest inValue = new ASMXinSharePointEr.CASService.isTokenAuthorizedForMethodRequest();
            inValue.SoapToken = SoapToken;
            inValue.MethodName = MethodName;
            return ((ASMXinSharePointEr.CASService.IntegrationService_UserSoap)(this)).isTokenAuthorizedForMethodAsync(inValue);
        }
    }
}
